
url: "https://www.encompassresearch.org"
baseurl: ""

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  authors:
    output: true
    permalink: /:name
  researchers:
    output: true
    permalink: /:name
  advisors:
    output: true
    permalink: /:name
  publications:
    output: false

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "advisors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "researchers"
    values:
      layout: "author"


sass:
  sass_dir: _sass
  style: compressed