#-------------------------------
# Site Settings
title: Encompass
description: Encompass Website
logo: "/images/logo.png"
logo_dark:
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "About"
      url: "/about/"
    - title: "Meet the team"
      url: "/team/"
    - title: "Research & Publications"
      url: "/research-and-publications/"
    - title: "News & Updates"
      url: "/news-and-updates/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: 'mailto:kirsty.prest@gmail.com'
  cta_button_text: Get in touch

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Supporting Families of Children with Complex Neurodisability
  hero_description: We’re working with parents, health professionals, and researchers to co-adapt and pilot test the "Baby Ubuntu" programme for families of children with complex neurodisability (such as cerebral palsy) in East London, United Kingdom. This is the first time "Baby Ubuntu" has been adapted for a high-income setting. Our programme is called "Encompass" which is a 10-module participatory group programme facilitated by a healthcare professionals and parents with lived experience. "Encompass" aims to support parents, caregivers and families in navigating the journey of caring for a child with complex neurodisability. 

hero_researchers:
  enable: true
  hero_researchers_description: Meet our team

#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Research & Publications

#-------------------------------
# Authors Section Settings
authors:
  enable: true
  authors_title: Top authors

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Stay Inspired Weekly. Your Friendly Dose of Tips & Insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Footer Settings

# Social Links
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://x.com/kirstprestot"}

# Funders Links
funders:
  - {image: "/images/funders/harp.png", name: "Harp", link: "https://harpphd.org/"}
  - {image: "/images/funders/city.png", name: "Harp", link: "https://www.citystgeorges.ac.uk/"}
  - {image: "/images/funders/ubuntu.png", name: "Harp", link: "https://www.ubuntu-hub.org/"}
  - {image: "/images/funders/ucl.svg", name: "UCL", link: "https://www.ucl.ac.uk/"}

#-------------------------------
# Contact Settings
contact:
  form_id: your@email.com # Add your form_id
  title: Contact Us
  description: Encompass comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free.
  button_text: Send now

# NOTE


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id